swagger: "2.0"
info:
  version: "v1"
  title: TOPIC相关 API
  description: 流数据总线topic相关信息接口

basePath: /regions/{regionId} 

paths:
  "/topicList":
  ###################### 查询topic接口 ######################
    get:
      description: "查询topic"
      operationId: getTopicList
      parameters:
        - name: keyword
          in: query
          type: string
          required: false
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  topic:
                    type: array
                    items:
                      type: object
                      $ref: "../model/topicListInfo.yaml#/definitions/topicListInfo"
              requestId:
                type: string
        401:
          description: ERROR
          
  "/topic":
  ###################### 创建topic接口 ######################
    post:
      description: "创建topic"
      operationId: addTopic
      parameters:
        - name: topicModel
          in: body
          required: true
          schema:
            $ref: "../model/addOrUpdateTopic.yaml#/definitions/addTopic"
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                    description: "状态信息"
              requestId:
                type: string
        400:
          description: ERROR
                
  ###################### 更新topic接口 ######################
    put:
      description: "更新topic"
      operationId: updateTopic
      parameters:
        - name: topicModel
          in: body
          required: true
          schema:
            $ref: "../model/addOrUpdateTopic.yaml#/definitions/addTopic"
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                    description: "状态信息"
              requestId:
                type: string
        400:
          description: ERROR
###################### 删除topic接口 ######################
    delete:
      description: "删除topic"
      operationId: deleteTopic
      parameters:
        - name: name
          in: query
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                    description: "状态信息"
              requestId:
                type: string
        400:
          description: ERROR  
  ###################### 查看指定主题 ######################
    get:
      description: "查看指定主题"
      operationId: describeTopic
      parameters:
        - name: name
          in: query
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                    topic:
                      type: object
                      $ref: "../model/addOrUpdateTopic.yaml#/definitions/addTopic"
              requestId:
                type: string
        400:
          description: ERROR
                                
#路径通用参数
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID