swagger: "2.0"
definitions:
  addTopic:
    x-jdcloud-module: streambus
    title: addTopic
    type: object
    properties:
      topic:
        type: object
        $ref: "../model/topic.yaml#/definitions/topic"
      target:
        type: object
        $ref: "../model/target.yaml#/definitions/target"
      parameterList:
        type: array
        description: "归档相关的具体参数"
        items:
          type: object
          $ref: "../model/parameterList.yaml#/definitions/parameterList"