swagger: '2.0'
definitions:
  storage:
    x-jdcloud-module: streamcomputer
    title: storage
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      uid:
        type: string
      type:
        type: string
      storageType:
        type: string
      userName:
        type: string
      createTime:
        type: string
        format: date
      updateTime:
        type: string
        format: date  
      namespaceId:
        type: string
      deleted:
        type: string
        format: byte
      storageParameterList:
        type: array
        items:
            $ref: "../model/StorageParameter.yaml#/definitions/storageParameter"
            
 